public class WayToWriteAClass {
	/* Description :- 
	*
    */
    
    
    // ATTRIBUTES
    public String oppId {get;set;}
    public final Integer LOOP_RUN_CONSTANT = 10;
    public final String ERROR_EMAIL_ALERT = Label.ERROR_EMAIL_FALG;
    
    
    // CONTRUCTOR
    public WayToWriteAClass(){
       
    }
    
    
    public WayToWriteAClass(String smp){
       
    }
    
    // METHODS
    
    
    /* This method does sum of two variables and return the value
     * Written by Vivek
     * 
	*/
    public Integer returnSum(Integer a,Integer b){
        
        for(Integer loop_var = 0; loop_var <LOOP_RUN_CONSTANT ; loop_var ++ ){
            
        }
        
        return (a+b);
    }    
    
    // WRAPPER
}